### ISSUE TITLE
Hauptmenü erstellen

### ISSUE THREAD

**Issue by Cinnay1621** [HerrSturm/EckenerProject#28]
Für eine angenehme Spielerfahrung wird ein Hauptmenu von uns, den obersten Zweien, angeordnet.

**Comment by HerrSturm** [comment]
Aufgaben:

- Erstellen eines Hauptmenü mit Design, das bei Ausführung der main.py geöffnet wird. 
-> Erstellen Sie eine Funktion, die das Hauptmenü anzeigen lässt
-> Hauptmenü lässt Spiel starten und wird nach Beendigung des Spiels wieder angezeigt
-> Programm kann über das Menü geschlossen werden
-> Überlegen Sie sich eine Möglichkeit der Navigation in Menü Tastatur / Maus
-> ggf. müssen Sie in der Pygame Dokumentation nachsehen, wie man die Maussteuerung umsetzen kann


- main.py muss so umstrukturiert werden, dass Ihre Funktion zur Anzeige des Hauptmenüs aufgerufen wird
- der Aufbau des Spielfeldes soll durch einen weiteren Funktionsaufruf geschehen. Bauen Sie dazu die main.py so um, dass die Initialisierung und das Handling des Spielfeldes in eine Funktion verschoben wird, diese Funktion soll dann auch aufgerufen werden, wenn das Spiel gestartet wird

- Optional: Öffnen des Menüs aus dem Spiel heraus ermöglichen

**Comment by HerrSturm** [comment]
Folgende Probleme liegen vor:
- Sie haben eine while True Schleife in menu.py, die beim Import schon aufgerufen wird und somit alles weitere blockiert.
- Die Aktivierung Ihres Menüs würde ich über eine paused Variable regeln, statt über die Klasse, führen Sie diese in menu.py ein, dann können Sie diese in main.py mit menu.paused abfragen (Wenn Sie die Klasse statt des Booleans trotzdem verwenden wollen, müssen Sie noch "from enum import Enum" in der main ergänzen)
- Nutzen von mainScreen =  pygame.display.get_surface() um aktiven Screen zu bekommen
- Fall Sie Mausabfragen einsetzen wollen verwenden Sie:

           pygame.event.get()
           pygame.mouse.get_pressed()[0]              ([0] für linke Maustaste)
           pygame.mouse.get_pos()[koordinate]      ([0] für x-Koordinate, [1] für y-Koordinate)
Setzen Sie diese in der Funktion menu() ein

**Comment by HerrSturm** [comment]
Eine Sache, die Sie noch recherchieren können ist das Key Up event um das Menü zu öffnen oder zu schließen, da die get_pressed() Variante für die Keys teilweise mehrfach Tastendrücke in den Queue packt.
