### ISSUE TITLE
Leben soll auch abgezogen werden, wenn der Gegner gegen den Charakter läuft (bei jeder Berührung)

### ISSUE THREAD

**Issue by HerrSturm** [HerrSturm/EckenerProject#68]

**Comment by MariusDoe** [comment]
Ich halte es für sinnvoller wenn der Charakter auch Leben verliert, wenn er auf dem Gegner steht oder wenn der Gegner gegen den Charakter läuft. Der Gegner selbst ist ja tödlich, nicht das Laufen gegen ihn...?

**Comment by HerrSturm** [comment]
Ja, da habe ich mich ungünstig ausgedrückt. Der Bug ist, dass das Leben nur bei einer aktiven Bewegung des Charakters abgezogen wird, nicht, wenn der Gegner gegen den Charakter läuft.
Ich bennen den Issue mal sinnvoll.

**Comment by MariusDoe** [comment]
#89
