### ISSUE TITLE
Gameklasse mit Zuständen implementieren

### ISSUE THREAD

**Issue by HerrSturm** [HerrSturm/EckenerProject#69]
Eine Oberklasse für das Spiel soll implementiert werden, die mittels Zuständen verwaltet, was auf dem Screen dargestellt wird.

Dazu muss die Menü Klasse eingearbeitet werden.

Für die Zustände sollten Enum genutzt werden.

**Comment by HerrSturm** [comment]
Bitte zusammenarbeiten, damit die Menüklasse die erforderlichen Zustände zurückgibt. Nutzen Sie Slack für den Austausch.

**Comment by MariusDoe** [comment]
#84
